# See https://fly.io/docs/reference/configuration/
# for information about how to use this file.

app            = 'twiga'
primary_region = 'ams'

[build]

[http_service]
  internal_port        = 7860
  force_https          = true
  auto_stop_machines   = 'off'
  auto_start_machines  = true
  min_machines_running = 0

  [http_service.concurrency]
    type       = 'requests'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size   = 'shared-cpu-8x'
  memory = '8gb'
